http:
  routers:
    to-app:
      rule: "HostRegexp(`dev.localhost`, `{subdomain:[a-z]+}.dev.localhost`)"
      service: app
      tls: {}

  services:
    app:
      loadBalancer:
        servers:
          - url: {{ expandenv "${APP_URL}" }}