log:
  level: INFO
  format: common

api:
  debug: true
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  file:
    directory: /configs

global:
  sendAnonymousUsage: false
